// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AddRepo: typeof import('./src/components/AddRepo.vue')['default']
    Copyright: typeof import('./src/components/Copyright.vue')['default']
    Depiction: typeof import('./src/components/Depiction.vue')['default']
    ListItemGroup: typeof import('./src/components/ListItemGroup.vue')['default']
    PackageUpdates: typeof import('./src/components/PackageUpdates.vue')['default']
    SectionList: typeof import('./src/components/SectionList.vue')['default']
    SocialShare: typeof import('./src/components/SocialShare.vue')['default']
    ThemeChange: typeof import('./src/components/ThemeChange.vue')['default']
  }
}

export { }
